version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0
    environment:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - run:
          name: Confirm Ruby version
          command: ruby -v

workflows:
  version: 2
  default:
    jobs:
      - build
